### ISSUE TITLE
hello,There is an error here

### ISSUE THREAD

**Issue by Funny-dot** [siutin/stable-diffusion-webui-docker#1]
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: ea9bd9fc7409109adcd61b897abc2c8881161256
Installing requirements for Web UI
Launching Web UI with arguments: --precision full --no-half --use-cpu SD GFPGAN BSRGAN ESRGAN SCUNet --all --share
/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: HIP initialization: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice (Triggered internally at ../c10/hip/HIPFunctions.cpp:110.)
  return torch._C._cuda_getDeviceCount() > 0
Warning: caught exception 'Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice', memory monitor disabled
No module 'xformers'. Proceeding without it.
No checkpoints found. When searching for checkpoints, looked at:
 - file /app/stable-diffusion-webui/model.ckpt
 - directory /app/stable-diffusion-webui/models/Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations. The program will exit.

this is run code:
`docker run -it --name sdw --network host \
>   -v /www/wwwroot/ai/public/models:/app/stable-diffusion-webui/models \
>   -v /www/wwwroot/ai/public/outputs:/app/stable-diffusion-webui/outputs \
>   --rm siutin/stable-diffusion-webui-docker \
>   bash webui.sh --skip-torch-cuda-test --precision full --no-half --use-cpu SD GFPGAN BSRGAN ESRGAN SCUNet --all --share
`

help me !thinks.

**Comment by siutin** [comment]
Not a bug, you should run it with a pretrained model.
