### ISSUE TITLE
How to modify a listening address

### ISSUE THREAD

**Issue by utopeadia** [siutin/stable-diffusion-webui-docker#13]
I need to deploy on a server. I noticed that the listening address is 127.0.0.1. Can you specify or modify it to 0.0.0.0? if you use 127.0.0.1, it will cause the public network to be inaccessible.

**Comment by mvstrawn** [comment]
@how1ewu If you've not figured this out yet and still want to use this container,

You would use the parameter:
--add_host "127.0.0.1:0.0.0.0"

Reference: https://docs.docker.com/engine/reference/commandline/run/

Or in docker-compose,
extra_hosts:
  - "127.0.0.1:0.0.0.0"

Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/#extra_hosts

**Comment by siutin** [comment]
just add "--listen" to the command
