### ISSUE TITLE
目前已经无法安装了,会卡在下载的步骤

### ISSUE THREAD

**Issue by dycwuxing** [siutin/stable-diffusion-webui-docker#14]
会提示如下内容,手动打开发现无法访问frpc_linux_aarch64这个连接

Could not create share link. Missing file: /app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/frpc_linux_aarch64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_aarch64
2. Rename the downloaded file to: frpc_linux_aarch64_v0.2
3. Move the file to this location: /app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio

**Comment by siutin** [comment]
試一下把 ”--share" 拿掉

**Comment by dycwuxing** [comment]
去掉了,会一直停留在这里,然后我用公网IP+端口http://XXXX:7860没法大概,大佬请问该怎么做?谢谢~

<img width="1283" alt="image" src="https://github.com/siutin/stable-diffusion-webui-docker/assets/44988562/85161100-194c-4e5d-abe9-74029c4d61f8">

**Comment by siutin** [comment]
可以使用 "--listen"

**Comment by dycwuxing** [comment]
> 可以使用 "--listen"

已经可以了,非常感谢!
