### ISSUE TITLE
请问下如何安装ffmpeg

### ISSUE THREAD

**Issue by skyliwq** [siutin/stable-diffusion-webui-docker#20]
$ sudo apt install ffmpeg
ERROR: ld.so: object '/usr/lib/libtcmalloc.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ffmpeg
请问下如何安装ffmpeg

**Comment by siutin** [comment]
先更新一下
`apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg`
