### ISSUE TITLE
Permission denied: '/app/stable-diffusion-webui/models/hypernetworks'`

### ISSUE THREAD

**Issue by breakenknife** [siutin/stable-diffusion-webui-docker#3]
hello I got a permission error: 
`ubuntu@VM-0-3-ubuntu:~/sd$ sudo docker run -it --name sdw --network host \
>   -v $(pwd)/models:/app/stable-diffusion-webui/models \
>   -v $(pwd)/outputs:/app/stable-diffusion-webui/outputs \
>   --rm siutin/stable-diffusion-webui-docker \
on full --no-half --use-cpu SD GFPGAN BSRGAN ESRGAN SCUNet --all --share>   bash webui.sh --skip-torch-cuda-test --precision full --no-half --use-cpu SD GFPGAN BSRGAN ESRGAN SCUNet --all --share

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on app user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: ea9bd9fc7409109adcd61b897abc2c8881161256
Installing requirements for Web UI
Launching Web UI with arguments: --precision full --no-half --use-cpu SD GFPGAN BSRGAN ESRGAN SCUNet --all --share
/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: HIP initialization: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice (Triggered internally at ../c10/hip/HIPFunctions.cpp:110.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/launch.py", line 361, in <module>
    start()
  File "/app/stable-diffusion-webui/launch.py", line 352, in start
    import webui
  File "/app/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/app/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/app/stable-diffusion-webui/modules/shared.py", line 155, in <module>
    os.makedirs(cmd_opts.hypernetwork_dir, exist_ok=True)
  File "/app/miniconda3/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/stable-diffusion-webui/models/hypernetworks'`

**Comment by breakenknife** [comment]
and the permission of folder models and hypernetworks  both been set to drwxrwxrwx

**Comment by siutin** [comment]
@breakenknife  You might need to set the current folder's permissions to drwxrwxrwx'as well. Another approach would be to assign folders ownership to the application user:

sudo chown 10000:$UID -R models outputs
