### ISSUE TITLE
docker run 报错没有权限

### ISSUE THREAD

**Issue by zhangdongdong7** [siutin/stable-diffusion-webui-docker#4]
你好，麻烦看看为啥docker run报错没权限
<img width="704" alt="image" src="https://github.com/siutin/stable-diffusion-webui-docker/assets/40697450/38b66f6b-bb2e-486d-a15e-30b94bfc6721">

我尝试自己手动打镜像，也失败
<img width="973" alt="image" src="https://github.com/siutin/stable-diffusion-webui-docker/assets/40697450/5a19a846-c70d-4959-aa7d-36bd03f8bdf4">

**Comment by cyijun** [comment]
chmod试试

**Comment by siutin** [comment]
試一下
sudo chown 10000:$UID -R models outputs
