### ISSUE TITLE
最新release的webui.sh停不下来

### ISSUE THREAD

**Issue by cyijun** [siutin/stable-diffusion-webui-docker#5]
## clone最新webui仓库的现象，根本停不下来
![image](https://github.com/siutin/stable-diffusion-webui-docker/assets/42707013/b772210a-fbcd-42d6-a82b-de90aab9f507)

## 后面加一条git checkout到1.1.0版本，正常停下
![image](https://github.com/siutin/stable-diffusion-webui-docker/assets/42707013/d513c806-7673-4ac0-9598-d7d054f7229c)

**Comment by siutin** [comment]
Fixed
